name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x
    
    - name: Restore NuGet packages
      run: dotnet restore
    
    - name: Build the project
      run: dotnet build --configuration Release
    
    - name: Test the project
      run: dotnet test
    
    # - name: Publish Artifact for Windows
    #   if: success() && runner.os == 'Windows'
    #   run: dotnet publish -c Release -o ./publish-win
    #   working-directory: ./

    - name: Setup Keychain
      if: success() && runner.os == 'macos'
      run: |
        security create-keychain -p "${{ secrets.KEYCHAIN_PASSWORD}}" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "${{ secrets.KEYCHAIN_PASSWORD}}" build.keychain
        echo "${{ secrets.MACOS_CERTIFICATE }}" | base64 --decode > certificate.p12
        security import certificate.p12 -k build.keychain -P "${{ secrets.MACOS_CERTIFICATE_PWD}}" -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "${{ secrets.KEYCHAIN_PASSWORD}}" build.keychain
        xcrun notarytool store-credentials "AC_PASSWORD" --apple-id "${{ secrets.APPLE_ID }}" --team-id "${{ env.TEAM_ID }}" --password "${{ secrets.NOTARY_TOOL_PASSWORD }}"

    - name: Publish Artifact on Mac
      if: success() && runner.os == 'macos'
      run: dotnet publish -c Release -o $RUNNER_TEMP/MyApp.app/Contents/MacOS --self-contained -r osx-x64 /p:PublishSingleFile=true 
      working-directory: ./
    
    - name: Codesign app
      run: |
        find "$RUNNER_TEMP/MyApp.app/Contents/MacOS/"|while read fname; do
          if [ -f "$fname" ]
          then
              echo "[INFO] Signing $fname"
              codesign --force --timestamp --options=runtime --entitlements MyApp.entitlements --sign "${{ env.SIGNING_IDENTITY }}" "$fname"
          fi
        done
        codesign --force --timestamp --options=runtime --entitlements MyApp.entitlements --sign "${{ env.SIGNING_IDENTITY }}" "$RUNNER_TEMP/MyApp.app"
    
    # - name: Upload Artifact Windows
    #   if: success()
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: avalonia-app-win
    #     path: ./publish-win
    
    - name: Upload Artifact Mac
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: avalonia-app-mac
        path: ./publish-mac
