name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@1
      with:
        dotnet-version: 7.x
    
    - name: Restore NuGet packages
      run: dotnet restore
    
    - name: Build the project
      run: dotnet build --configuration Release
    
    - name: Test the project
      run: dotnet test
    
    - name: Publish Artifact
      if: success()
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          dotnet publish -c Release -o ./publish
        else
          dotnet publish -c Release -o ./publish --self-contained -r osx-64
        fi
      working-directory: ./
    
    - name: Upload Artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: avalonia-app
        path: ./publish
