name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x
    
    - name: Restore NuGet packages
      run: dotnet restore
    
    - name: Build the project
      run: dotnet build --configuration Release
    
    - name: Test the project
      run: dotnet test
    
    # - name: Publish Artifact for Windows
    #   if: success() && runner.os == 'Windows'
    #   run: dotnet publish -c Release -o ./publish-win
    #   working-directory: ./

    - name: Publish Artifact on Mac
      if: success() && runner.os == 'macos'
      run: dotnet publish -c Release -o ./publish-mac --self-contained -r osx-x64 /p:PublishSingleFile=true 
      working-directory: ./
    
    # - name: Upload Artifact Windows
    #   if: success()
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: avalonia-app-win
    #     path: ./publish-win
    
    - name: Upload Artifact Mac
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: avalonia-app-mac
        path: ./publish-mac
